### ISSUE TITLE
Persistence Broken

### ISSUE THREAD

**Issue by jerkinmerkin** [Spearhead-Gaming-Milsim/Queens-Stallions#45] opened 2016-12-16 21:11 UTC
So we know its not R3F.  Theres probably a conflict between ALiVE and some mod somewhere.  I'll work best I can to narrow down what it is but it will take time.  Probably won't have it fixed before launch.

**Comment by coachwn** [comment] 2016-12-16 21:29
Was working on it earlier and unable to track down exactly where in the location for the problem. Haven't pulled the RPT yet to go through it.

**Comment by jerkinmerkin** [comment] 2016-12-17 01:51
Tested all the way down to just Alive and CBA.  Still didn't work.  So it's not a mod conflict.  It might be TADST like we were recently thinking.  Will test further.

**Comment by jerkinmerkin** [comment] 2016-12-17 02:30
Don't have any time to test without TADST tonight, y'all have to take care of that before launch

**Comment by coachwn** [comment] 2016-12-17 06:19
Still does not appear to be working...Have tried 2 saves now with it and still same result of vehicles not staying in correct place.

**Comment by coachwn** [comment] 2016-12-17 06:31
SSMP not working at the moment with I guess v14 on it....moved everything back to TADST for the mission launch. If nothing else we will move ahead and not worry about persistence for Saturday until whenever we get it working.

**Comment by jerkinmerkin** [comment] 2016-12-17 10:36
Okay, can we set up the rest server so that it launches with a .bat file like on Noble Resolve and Sultans Wrath?  Persistence worked then, let's see if it'll work again if we launch that way.  Also, did falcon add any new firewalls or something to the box?  Could be that too.

**Comment by jerkinmerkin** [comment] 2016-12-17 12:22
Test*

**Comment by jerkinmerkin** [comment] 2016-12-18 15:49
So uhhhh I might have fixed it (!!!!!!!!!!!!!!!!!!!)

**Comment by jerkinmerkin** [comment] 2016-12-18 15:55
I have successfully persisted the test mission with the Player Logistics module placed down.

**Comment by coachwn** [comment] 2016-12-18 16:24
Do tell...what broke vehicle persistence?

**Comment by jerkinmerkin** [comment] 2016-12-18 16:25
Still narrowing it down.  That was with just ALiVE and CBA.  Now trying to get it to work with all the mods... and it broke again.  The hunt continues, but we know it works now.

**Comment by jerkinmerkin** [comment] 2016-12-18 16:55
So, I made a new War Room for the test server.  That seemed to make the player logistics module work.  R3F seems to have breaking it too.  Now had a successful save with all the mods running but R3F removed.

**Comment by jerkinmerkin** [comment] 2016-12-18 17:42
Good new, Queen's Horses persisted on the test server.  Will let it run for a while and then try and save again.

**Comment by jerkinmerkin** [comment] 2016-12-18 23:21
So after letting the server run for several hours I tested saving... and it worked!!!  Although I haven't tried playing around a killing things, I'd say I'm 90% sure its going to work now.  Shall I push this to the milsim side?  We might have to do a hard reset since R3F is present on this mission.

**Comment by jerkinmerkin** [comment] 2016-12-23 15:19
Milsim server persistence set up and working.

**Comment by FoxKilo** [comment] 2016-12-27 00:46
War room hasn't received any data since the 23rd December (4 days ago), query if persistence is broken.

**Comment by coachwn** [comment] 2016-12-27 14:06
Will take a look at it today. Haven't had a chance to get to the server remotely for a few days and need to get caught up on some stuff here.

**Comment by FoxKilo** [comment] 2016-12-30 20:17
War room is still not reporting, server has been up for 141 hours at this point. Player data is still being collected by clients and uploaded to group stats but nothing else is.

Any objections to doing a server save tonight let me know, otherwise i'll create a snapshot of the server now and prepare for a save and hard restart, prior to tomorrow's mission if people get on.

Server performance is still showing good stats but in-game i'm noticing an average 10-15 frame drop + sync issues by the time the server has been up for 3+ days. Bi-weekly saving is advised.

**Comment by coachwn** [comment] 2016-12-30 20:37
I think we probably go no longer than 72 hours between saves honestly. I am looking into the war room aspect since it was reporting before last weekends op and mission adjustments.

**Comment by coachwn** [comment] 2016-12-30 20:38
I may redo the alive.cfg file here in a little bit and see what happens.

**Comment by FoxKilo** [comment] 2016-12-30 20:41
Snapshot is taken and posted on continuity thread. All good to do a hard restart?

**Comment by jerkinmerkin** [comment] 2016-12-30 21:51
It's on a new, working war room.  Do not replace the alive.cfg.

**Comment by coachwn** [comment] 2016-12-30 22:28
So why did it get changed? The main room from the test was functioning correctly from what u saw as far as reporting goes. I have already asked Tupolov to purge all spearhead group data from the database.

**Comment by jerkinmerkin** [comment] 2016-12-30 23:04
I don't know why your war room wasn't working, but when I made a new one and connected to that persistence started working again.

**Comment by coachwn** [comment] 2016-12-30 23:07
Ok well for some reason when Fox saved it the one you had didn't return all the values either. That is why I am asking Tup to purge all the database information for anything related to Spearhead

**Comment by FoxKilo** [comment] 2017-01-01 02:58
Since last week implementing v16, the war room switched from the recent spearhead one people subscribed to, to the newer one jerkin created when workin on the fix during v15. So since last week all the stats have been recorded on jerkin's war room. Easy fix is to get everyone to join jerkin's war room, longer fix is to figure out which module or config needs to be changed to point it back to the current war room. Either way i've manually reinstallled persistence to a level that people will only notice a difference within their boxes. Merry christmas from a drunk limey, see ya'll in the new year.

**Comment by FoxKilo** [comment] 2017-01-08 16:08
sys_data not connecting to the DB, as per previous post the milsim server was still reporting to jerkin's test war room, but has since stopped reporting 1 week ago due to the sys_data module not reporting data to the war room.

**Comment by coachwn** [comment] 2017-01-08 17:58
[Check this out...](http://alivemod.com/forum/2665-player-logistics-future/0#p17703) I think this guy is from the R3F community as he was asking me questions about ALiVE after I posted in the R3F thread on BI forums.

**Comment by FoxKilo** [comment] 2017-01-09 22:51
Managed to get persistence working tonight including recovering from a successful save. Working theory is that our hard restarts are corrupting the saves, since the mission will do a semi-hard reload as soon as you get kicked from the server.

Will investigate further but for now I will reimplement persistence and reproduce a successful save with a fully loaded base.

**Comment by FoxKilo** [comment] 2017-01-10 00:13
ALiVE has reproduced a successful save with a fully reconstructed base and manual persistence saves. I can finally close this thread again until something breaks it in 4 days time.

**Closed by FoxKilo** 2017-01-10 00:13 UTC
Labels: Bug, High Priority
